#!/usr/bin/env node

/**
 * VibeSynth GitHub Pages Deployment Script (Node.js)
 * Copies the 4 main files needed for GitHub Pages to /docs folder
 */

const fs = require('fs');
const path = require('path');

console.log('🚀 VibeSynth GitHub Pages Deployment');
console.log('=====================================');

// Define the main files needed for GitHub Pages
const MAIN_FILES = [
    'index.html',
    'script.js', 
    'style.css',
    'layout.js'
];

const ADDITIONAL_FILES = [
    'favicon.ico',
    'vibesynth-logo.png'
];

const FOLDERS = [
    'presets'
];

function copyFileSync(src, dest) {
    try {
        fs.copyFileSync(src, dest);
        return true;
    } catch (error) {
        console.error(`❌ Error copying ${src}:`, error.message);
        return false;
    }
}

function copyFolderSync(src, dest) {
    try {
        if (!fs.existsSync(dest)) {
            fs.mkdirSync(dest, { recursive: true });
        }
        
        const items = fs.readdirSync(src);
        
        for (const item of items) {
            const srcPath = path.join(src, item);
            const destPath = path.join(dest, item);
            
            if (fs.statSync(srcPath).isDirectory()) {
                copyFolderSync(srcPath, destPath);
            } else {
                copyFileSync(srcPath, destPath);
            }
        }
        return true;
    } catch (error) {
        console.error(`❌ Error copying folder ${src}:`, error.message);
        return false;
    }
}

// Create docs directory if it doesn't exist
const docsDir = 'docs';
if (!fs.existsSync(docsDir)) {
    console.log('📁 Creating docs directory...');
    fs.mkdirSync(docsDir);
} else {
    console.log('📁 docs directory already exists');
}

// Copy main files to docs folder
console.log('📋 Copying main files to docs folder...');
let success = true;

for (const file of MAIN_FILES) {
    if (fs.existsSync(file)) {
        if (copyFileSync(file, path.join(docsDir, file))) {
            console.log(`✅ Copied: ${file}`);
        } else {
            success = false;
        }
    } else {
        console.log(`❌ Missing: ${file}`);
        success = false;
    }
}

if (!success) {
    console.error('❌ Failed to copy main files. Exiting.');
    process.exit(1);
}

// Copy additional assets if they exist
console.log('🎨 Copying additional assets...');

for (const file of ADDITIONAL_FILES) {
    if (fs.existsSync(file)) {
        if (copyFileSync(file, path.join(docsDir, file))) {
            console.log(`✅ Copied: ${file}`);
        }
    }
}

// Copy folders if they exist
for (const folder of FOLDERS) {
    if (fs.existsSync(folder) && fs.statSync(folder).isDirectory()) {
        if (copyFolderSync(folder, path.join(docsDir, folder))) {
            console.log(`✅ Copied: ${folder}/ folder`);
        }
    }
}

// Create a simple README for the docs folder
const readmeContent = `# VibeSynth GitHub Pages

This folder contains the deployable files for VibeSynth on GitHub Pages.

## Files:
- \`index.html\` - Main application page
- \`script.js\` - Core application logic and WebGL engine
- \`style.css\` - Application styling
- \`layout.js\` - Graph layout algorithms
- \`presets/\` - Preset configurations (if available)

## Auto-generated
This folder is automatically generated by \`deploy-docs.js\` or \`deploy-docs.sh\`. 
Do not edit files here directly - edit the source files in the project root.

## GitHub Pages Setup
1. Go to repository Settings > Pages
2. Set Source to "Deploy from a branch"
3. Select "main" branch and "/docs" folder
4. Save and wait for deployment

Last updated: ${new Date().toISOString()}
`;

fs.writeFileSync(path.join(docsDir, 'README.md'), readmeContent);
console.log('📝 Created docs/README.md');

// Display summary
console.log('');
console.log('📊 Deployment Summary:');
console.log('======================');
console.log(`📁 Target folder: ${docsDir}/`);
console.log(`📄 Files copied: ${MAIN_FILES.length} main files`);

// List all files in docs folder
console.log('');
console.log('📋 Files in docs folder:');
try {
    const files = fs.readdirSync(docsDir);
    files.forEach(file => {
        const filePath = path.join(docsDir, file);
        const stats = fs.statSync(filePath);
        const type = stats.isDirectory() ? '[DIR]' : '[FILE]';
        const size = stats.isDirectory() ? '' : ` (${Math.round(stats.size / 1024)}KB)`;
        console.log(`  ${type} ${file}${size}`);
    });
} catch (error) {
    console.error('❌ Error listing docs folder:', error.message);
}

console.log('');
console.log('🎉 GitHub Pages deployment ready!');
console.log('💡 Next steps:');
console.log('   1. Commit these changes: git add docs/ && git commit -m "Add GitHub Pages deployment"');
console.log('   2. Push to GitHub: git push');
console.log('   3. Enable GitHub Pages in repository settings (Settings > Pages > Source: main/docs)');
console.log('');