#!/bin/bash

# VibeSynth GitHub Pages Deployment Script
# Copies the 4 main files needed for GitHub Pages to /docs folder

echo "🚀 VibeSynth GitHub Pages Deployment"
echo "====================================="

# Define the main files needed for GitHub Pages
MAIN_FILES=(
    "index.html"
    "script.js" 
    "style.css"
    "layout.js"
)

# Create docs directory if it doesn't exist
if [ ! -d "docs" ]; then
    echo "📁 Creating docs directory..."
    mkdir docs
else
    echo "📁 docs directory already exists"
fi

# Copy main files to docs folder
echo "📋 Copying main files to docs folder..."
for file in "${MAIN_FILES[@]}"; do
    if [ -f "$file" ]; then
        cp "$file" "docs/"
        echo "✅ Copied: $file"
    else
        echo "❌ Missing: $file"
        exit 1
    fi
done

# Copy additional assets if they exist
echo "🎨 Copying additional assets..."

# Copy favicon if it exists
if [ -f "favicon.ico" ]; then
    cp "favicon.ico" "docs/"
    echo "✅ Copied: favicon.ico"
fi

# Copy logo if it exists
if [ -f "vibesynth-logo.png" ]; then
    cp "vibesynth-logo.png" "docs/"
    echo "✅ Copied: vibesynth-logo.png"
fi

# Copy presets folder if it exists
if [ -d "presets" ]; then
    cp -r "presets" "docs/"
    echo "✅ Copied: presets/ folder"
fi

# Create a simple README for the docs folder
cat > docs/README.md << EOF
# VibeSynth GitHub Pages

This folder contains the deployable files for VibeSynth on GitHub Pages.

## Files:
- \`index.html\` - Main application page
- \`script.js\` - Core application logic and WebGL engine
- \`style.css\` - Application styling
- \`layout.js\` - Graph layout algorithms
- \`presets/\` - Preset configurations (if available)

## Auto-generated
This folder is automatically generated by \`deploy-docs.sh\`. 
Do not edit files here directly - edit the source files in the project root.

## GitHub Pages Setup
1. Go to repository Settings > Pages
2. Set Source to "Deploy from a branch"
3. Select "main" branch and "/docs" folder
4. Save and wait for deployment

Last updated: $(date)
EOF

echo "📝 Created docs/README.md"

# Display summary
echo ""
echo "📊 Deployment Summary:"
echo "======================"
echo "📁 Target folder: docs/"
echo "📄 Files copied: ${#MAIN_FILES[@]} main files"

# List all files in docs folder
echo ""
echo "📋 Files in docs folder:"
ls -la docs/

echo ""
echo "🎉 GitHub Pages deployment ready!"
echo "💡 Next steps:"
echo "   1. Commit these changes: git add docs/ && git commit -m 'Add GitHub Pages deployment'"
echo "   2. Push to GitHub: git push"
echo "   3. Enable GitHub Pages in repository settings (Settings > Pages > Source: main/docs)"
echo ""